server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce_yujong?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        default_batch_fetch_size: 1000

  devtools:
    livereload:
      enabled: true

logging:
  level:
    org:
      springframework: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type: trace
    hibernate: DEBUG

